# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  projetweb.form.registration:
              class: ProjetWebBundle\Form\RegistrationType
              tags:
                  - { name: form.type, alias: projetweb_user_registration }

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
